require 'rubygems' if RUBY_VERSION < '1.9'
require 'fidius'

module FIDIUS
  class LabHelper
    def initialize
      load_plugin
      @lab = FIDIUS::Action::Msf.instance.framework.lab_api
    end

    def create_lab_config controller, path
      @lab.lab_load_config controller
      if File.exist? path
        puts "Autogenerated Lab Config already exists. Overwrite? Y/n"
        x = STDIN.getc    
        unless x.downcase == "y" || x == "\n"
          return 0
        end
      end
      if FIDIUS.config[:tests][:lab_config] != path && !FIDIUS.config[:tests][:lab_config].blank?
        puts "A custom Lab Config is specified in. Overwrite? Y/n"
        x = STDIN.getc    
        if x.downcase == "n"
          puts "Keeping old Config"
          return 0
        end
      end
      FIDIUS.config[:tests][:lab_config] = path
      FIDIUS.save
      @lab.lab_save path 
    end

    private
    def load_plugin
      FIDIUS::Action::Msf.instance.daemon.load_plugin "lab_api"
    end

  end

end
